services:
  mysql:
    image: mysql:8.0
    container_name: mysql_guias
    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - backend_network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: ${IMAGE_NAME}
    container_name: backend_guias
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "${SPRING_PORT}:8080"

    networks:
      - backend_network

volumes:
  mysql_data:

networks:
  backend_network:
